webtalk_init -webtalk_dir C:\\Users\\ChristopherSam\\XilinxProjects\\HelloEthernet\\HelloEthernet.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2025-04-23 11:31:20" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2018.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211583763_0_0_501" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "a324no8n2dqgi8m2atd0mtth2n" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2018.3_3" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2208 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.897 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1745380648597" -context "sdk\\\\bsp/1745380648597"
webtalk_add_data -client sdk -key hwid -value "1745378611141" -context "sdk\\\\bsp/1745380648597"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1745380648597"
webtalk_add_data -client sdk -key apptemplate -value "lwip_echo_server" -context "sdk\\\\bsp/1745380648597"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1745380648597"
webtalk_add_data -client sdk -key uid -value "1745380684899" -context "sdk\\\\bsp/1745380684899"
webtalk_add_data -client sdk -key hwid -value "1745378611141" -context "sdk\\\\bsp/1745380684899"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1745380684899"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\bsp/1745380684899"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1745380684899"
webtalk_add_data -client sdk -key uid -value "1745380686371" -context "sdk\\\\application/1745380686371"
webtalk_add_data -client sdk -key hwid -value "1745378611141" -context "sdk\\\\application/1745380686371"
webtalk_add_data -client sdk -key bspid -value "1745380684899" -context "sdk\\\\application/1745380686371"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1745380686371"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1745380686371"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\application/1745380686371"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1745380686371"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1745380686371"
webtalk_add_data -client sdk -key Procused -value "microblaze" -context "sdk\\\\application/1745380686371"
webtalk_add_data -client sdk -key projSize -value "102.2421875" -context "sdk\\\\application/1745380686371"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1745433080396"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1745433080396"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1745433080396"
webtalk_add_data -client sdk -key DebugCount -value "32" -context "sdk\\\\bsp/1745433080396"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1745433080396"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1745433080396"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1745433080396"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1745433080396"
webtalk_transmit -clientid 2750723086 -regid "211583763_0_0_501" -xml C:\\Users\\ChristopherSam\\XilinxProjects\\HelloEthernet\\HelloEthernet.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\Users\\ChristopherSam\\XilinxProjects\\HelloEthernet\\HelloEthernet.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\Users\\ChristopherSam\\XilinxProjects\\HelloEthernet\\HelloEthernet.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
